# this chart configuration

# Configuration of Ingress which triggers creation of a dedicated managed AWS load balancer
ingress:
  # Control if NGINX should be exposed using an Ingress for the AWS Load Balancer Controller
  enabled: true
  class: alb
  host: replace_me
  path: /
  pathType: Prefix
  service:
    name: ingress-nginx-controller
    port: 80

# Configuration of a TargetGroupBinding which binds NGINX to a target group of an existing potentially shared AWS load balancer
targetGroupBinding:
  # Control if NGINX should be exposed using a TargetGroupBinding
  enabled: false
  targetGroupArn: replace_me
  # Default target type is always ip to optimize routing between ALB and ingress controller pods
  targetType: ip
  service:
    name: ingress-nginx-controller
    port: 80

# Configuration of the AWS load balancer
loadbalancer:
  # AWS load balancer configuration exposed as ingress annotations
  # Ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/ingress/annotations/
  scheme: "internet-facing"
  name: replace_me
  targetType: "ip"
  backend:
    protocol: "HTTP"
  healthcheck:
    protocol: "HTTP"
    port: "traffic-port"
    path: "/healthz"
    intervalSeconds: "10"
    timeoutSeconds: "5"
    successCodes: "200,404"
  tls:
    certificateArn: replace_me
    sslPolicy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
  targetGroupSubnets: replace_me
