{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx-aws-extensions.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nginx-aws-extensions.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.loadbalancer.scheme }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.loadbalancer.name }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.loadbalancer.targetType }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.loadbalancer.targetGroupSubnets | quote }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.loadbalancer.backend.protocol }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.loadbalancer.healthcheck.protocol }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ .Values.loadbalancer.healthcheck.port | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.loadbalancer.healthcheck.path }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: {{ .Values.loadbalancer.healthcheck.intervalSeconds | quote }}
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: {{ .Values.loadbalancer.healthcheck.timeoutSeconds | quote }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.loadbalancer.healthcheck.successCodes | quote }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.loadbalancer.tls.certificateArn }}
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.loadbalancer.tls.sslPolicy }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.service.name }}
                port:
                  number: {{ .Values.ingress.service.port }}
{{- end }}
