{{- if .Values.targetGroupBinding.enabled -}}
{{- $fullName := include "nginx-aws-extensions.fullname" . -}}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nginx-aws-extensions.labels" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.targetGroupBinding.service.name }}
    port: {{ .Values.targetGroupBinding.service.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupArn }}
  targetType: {{ .Values.targetGroupBinding.targetType }}
{{- end }}
