apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-letsencrypt.fullname" . }}-staging
  labels:
    {{- include "cert-manager-letsencrypt.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.letsencrypt.acme.email }}
    server: {{ .Values.letsencrypt.acme.server.staging }}
    privateKeySecretRef:
      name: {{ include "cert-manager-letsencrypt.fullname" . }}-staging
    solvers:
      - dns01:
          route53:
            region: {{ .Values.letsencrypt.acme.route53.region }}
            hostedZoneID: {{ .Values.letsencrypt.acme.route53.hostedZoneId }}
